### ISSUE TITLE
Alternatywne ustawienie KAD

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KADAntiScam.netlify.app#13]
### Dodatkowe informacje mogące mieć znaczenie
Można na stronie uzupełnić o to, że także niektóre DNSy używają waszej listy hosts i można je alternatywnie używać (np. na urządzeniach mobilnych). Są to między innymi:
1. https://nextdns.io/ (zawiera bezpośrednio listę KAD i CERT w domyślnej konfiguracji)
2. https://ahadns.com/ (bazuje na oisd.nl)
3. https://dnscrypt.pl/ (zawiera bezpośrednio listę KAD i CERT)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
@krystian3w  - mały update. Wyśrodkowanie i punktory wyglądają trochę dziwacznie. Czcionka kolorystycznie zbyt nie miesza się z tłem? 

> Niektóre DNS-y używają naszej listy KADhosts i można je alternatywnie używać (np. na urządzeniach mobilnych). Są to między innymi:
> 
> * nextdns.io (zawiera bezpośrednio KADhosts w domyślnej konfiguracji, zalecamy dodatkowe włączenie „blokowanie nowo zarejestrowanych domen (NRD)” i opcjonalne dodanie listy blokowania reklam „CertyficateIT”)
> * libredns.gr (wersja z adblockiem*, bazuje na StevenBlack hosts)
> * ahadns.com (bazuje na oisd.nl)
> * adhole.org (bazuje na oisd.nl)
> * dnscrypt.pl (zawiera bezpośrednio listę KAD)

**Comment by krystian3w** [comment]
Mnie kolor nie wadzi, może za 50 lat już tak (mogę zrobić test kontrastu do rozmiaru (https://accessible-colors.com/), wyśrodkowanie jak namierzę dla sekcji to może wyłączę (albo brzydko się nadpisze w `style="..."`).

Punktory może lepiej będą wyglądać po wyrównaniu do lewej.

Cyfry wstępnie źle się formatują w szablonie:

![obraz](https://user-images.githubusercontent.com/35370833/102350108-af1c8380-3fa4-11eb-879a-f60611621d88.png) |
--- |

**Comment by hawkeye116477** [comment]
Fakt, dziwna sprawa, albowiem

Na Chromium jest tak
![2020-12-16_15-52](https://user-images.githubusercontent.com/19818572/102364520-d3815b80-3fb6-11eb-828c-ce447de6610c.png)
a na FF tak
![2020-12-16_15-53](https://user-images.githubusercontent.com/19818572/102364562-e09e4a80-3fb6-11eb-94d0-53acb015d3fe.png).

**Comment by krystian3w** [comment]
Firefox podobnie wyświetla 3/4 innych systemów niż `kwadrat`.

**Comment by AroKol78** [comment]
jak dla mnie - git
![kadino01](https://user-images.githubusercontent.com/70756447/102489052-3fbe9680-406d-11eb-979d-6d89a1b10c89.PNG)

**Comment by krystian3w** [comment]
Problem, że to zrzut najświeższego stanu po:

- dodaniu 5 znalezionych źródeł DNS
-  naprawie bugów na Chromium
- wyrównaniu do lewej
- akceptacji zwiększania kontrastu na `ratio` 4.52 / 5.40 (zależy jak ciemne jest tło).

**Comment by hawkeye116477** [comment]
Może to coś pomoże => https://getbootstrap.com/docs/4.4/content/typography/#responsive-font-sizes.

**Comment by AroKol78** [comment]
> jak dla mnie - git 

przy 1440 X 900 bez zoom

**Comment by hawkeye116477** [comment]
Nie wiem jak jest w starszych Windowsach, ale w 10 z automatu przy 4k ustawia skalę na 300% i wtedy jest git, choć ja mam TV 55 cali. Ze skalą 100% przy 4k raczej chyba nie ma w ogóle sensu korzystać, menu start, ikony, wszystko jest zbyt małe.

**Comment by AroKol78** [comment]
przy 1440 X 900 bez zoom - git
![kad010](https://user-images.githubusercontent.com/70756447/102689098-d8831c80-41fb-11eb-9783-3072b5d7c614.PNG)
![kad012](https://user-images.githubusercontent.com/70756447/102689101-dde06700-41fb-11eb-851f-f1ec3c35cb97.PNG)

**Comment by hawkeye116477** [comment]
Na tak niskich rozdzielczościach to raczej nie ma co gadać. 

@krystian3w mówił o wyższych i większych ekranach.

**Comment by krystian3w** [comment]
Full HD ma domyślnie DPI 96 (zoom 100%).

W sumie ciekawe jak Windows wykrywa że 4K na 55 calach ma mieć zoom 300% / DPI "288".

**Comment by AroKol78** [comment]
"Plug and play" tv/monitor

**Comment by ClusterByte-x** [comment]
**Aktualizacja**: `dnscrypt.pl` należy usunąć z listy. Po zmianach w projekcie lista KAD została usunięta. Proponuję dodać z powrotem jak zostanie uruchomione `dnscrypt.pl-armada`.

**Linki**:
> https://dnscrypt.pl/transparency/
> https://github.com/pysiak/dnscrypt.pl

**Comment by krystian3w** [comment]
Znaczy zamknięciu się do PL nas wywalili? A StevenBlack/hosts nie lubią bo zlepek? Czy oni lubili moduł "anty-fake-news"?

**Comment by hawkeye116477** [comment]
A CERT został. Może stwierdzili, że mamy za dobrą ochronę...

**Comment by ClusterByte-x** [comment]
Raczej `dnscrypt.pl-guardian` jest anty-phishing/malware, a `StevenBlack/host` wycina także reklamy, tracking, itd. Być może autor pomyślał, że `KAD` również?

**Comment by krystian3w** [comment]
Jeszcze jest taki wynalazek:

https://bravedns.com/configure -> https://rethinkdns.com/configure

Niby zrobili rebranding by nie kojarzyć się z Brave Browser albo nawet Mirindą (niezbyt) Waleczną.

Jedynie trzeba by namierzyć czy są otwarci na rozbudowanie subskrypcji.
