### ISSUE TITLE
Poprawki na kadantiscam.netlify.app

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KADAntiScam.netlify.app#18]
Proponuje usunąć proponowane DNS `ahadns.com` oraz `adhole.org` ze strony które korzystają z listy od `oisd.nl`. Oisd teraz korzysta z jakiegoś hostsa z KAD który nie jest aktualizowany od 2017 roku
https://raw.githubusercontent.com/migafgarcia/simplify-blocklist/master/blocklists/KADhosts.txt 
https://github.com/migafgarcia/simplify-blocklist/tree/master/blocklists

**Comment by krystian3w** [comment]
Jak sprawdzałem to dziwnym trafem lista zaczyna mieć nowsze wpisy z CERT, wątku o fejkowych sklepach czy ostrzeżeń ForexRev.

Jedynie martwiący jest fakt, braku domen jakie nasze PR zamknęło przy okazji - jakby twórca robił lepsze testy czy strona jest offline i eliminował wpis (więc jak zagraniczny DNS nie rozwiązuje domeny aktywnie działającej w Polsce to jego ochrona raczej jest do niczego).

**Comment by xMaap** [comment]
Napewno oisd.nl ma teraz listę od Cert w wersji Full nie widzę na przykład tego https://github.com/FiltersHeroes/KAD/commit/b928f18b5bdb6c04181c5017372dcfbc54576fac
`blitz-setup.ahadns.com` KAD jest w Energized (Spark), Energized (Blu), Energized (Basic), Energized (Ultimate), StevenBlack i na 90% w 1Hosts (Pro) oraz 1Hosts (Xtra).
Tylko co polecić włączyć aby komuś pół internetu nie rozwaliło.

**Comment by badmojr** [comment]
https://blocklist-tools.developerdan.com/entries/search?q=xeroshoes-polska.com

**Comment by xMaap** [comment]
Najmniej agresywny jest Energized Blu, ale i tak za dużo blokuje.
https://www.polsatnews.pl/wiadomosc/2021-12-24/wielka-brytania/?ref=kafle
![Zrzut ekranu z 2021-12-24 13-34-20](https://user-images.githubusercontent.com/36385327/147353020-6e7c12c7-1350-45ae-b87b-172845a2637a.png)

**Comment by krystian3w** [comment]
No to na razie odpuszczam.

**Comment by xMaap** [comment]
@krystian3w KAD wrócił do oisd.nl.

**Comment by hawkeye116477** [comment]
Tak czy siak, z tego co tu widzę => https://oisd.nl/includedlists, oni wywalają część wpisów z naszej listy, uznając to za niby fałszywe alarmy. Tak więc myślę, że nie warto dopisywać tego ponownie, skoro oni nie zgłaszają nic do nas, tylko sami przeprowadzają modyfikacje. Tym bardziej, że jak pobieżnie zerknąłem, nie uznałbym tych wpisów za fałszywe alarmy.

**Comment by krystian3w** [comment]
Gorzej jak nas wywalą za generowanie za dużo FP i wrócą na plik z 2017; podejrzewam, że tylko na reddicie zostawi info "wywaliliśmy najnowszy projekt KAD za mnóstwo FP".
